apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: data-product-platform
  title: Pharma Data Factory
  description: Standalone Data Product Factory built on Backstage.
  annotations:
    backstage.io/techdocs-ref: dir:.
    dataprod.platform/documentation-version: '1.0'
    dataprod.platform/documentation-reviewed: '2026-08'
  tags:
    - backstage
    - data-product-platform
spec:
  type: website
  owner: group:default/platform-team
  lifecycle: experimental
  system: data-platform
