"""Generic Data Product platform helpers. No source or storage logic."""

from dataprod.compatibility import (
    CompatibilityStatus,
    compare_schemas,
    compatibility_gate_should_fail,
    evaluate_compatibility,
    parse_semver,
    version_satisfies,
)
from dataprod.contracts import (
    is_iso8601,
    load_json,
    load_json_schema,
    normalize_iso8601,
    payload_matches_schema,
    schema_version,
    validate_against_schema,
)
from dataprod.metadata import (
    CERTIFICATION_STATUS_ANNOTATION,
    COMPATIBLE_VERSIONS_ANNOTATION,
    CONTRACT_ANNOTATION,
    CONTRACT_VERSION_ANNOTATION,
    DATA_PRODUCT_SDK_VERSION,
    DATA_PRODUCT_STANDARD_VERSION,
    QUALITY_STATUS_ANNOTATION,
    SDK_VERSION_ANNOTATION,
    STANDARD_VERSION_ANNOTATION,
    TEMPLATE_ANNOTATION,
    TEMPLATE_VERSION_ANNOTATION,
    PlatformMetadata,
    contract_api_entity_name,
    platform_metadata,
)
from dataprod.quality import (
    QualityCheck,
    QualityReport,
    quality_report,
    run_check,
    unique_field_check,
)

__all__ = [
    "CERTIFICATION_STATUS_ANNOTATION",
    "COMPATIBLE_VERSIONS_ANNOTATION",
    "CONTRACT_ANNOTATION",
    "CONTRACT_VERSION_ANNOTATION",
    "DATA_PRODUCT_SDK_VERSION",
    "DATA_PRODUCT_STANDARD_VERSION",
    "QUALITY_STATUS_ANNOTATION",
    "SDK_VERSION_ANNOTATION",
    "STANDARD_VERSION_ANNOTATION",
    "TEMPLATE_ANNOTATION",
    "TEMPLATE_VERSION_ANNOTATION",
    "CompatibilityStatus",
    "PlatformMetadata",
    "QualityCheck",
    "QualityReport",
    "compare_schemas",
    "compatibility_gate_should_fail",
    "contract_api_entity_name",
    "evaluate_compatibility",
    "is_iso8601",
    "load_json",
    "load_json_schema",
    "normalize_iso8601",
    "parse_semver",
    "payload_matches_schema",
    "platform_metadata",
    "quality_report",
    "run_check",
    "schema_version",
    "unique_field_check",
    "validate_against_schema",
    "version_satisfies",
]
