[pytest]
testpaths =
    operations/health/tests
    operations/observability/tests
    integration/rest-api/tests
    integration/rest-source/tests
    integration/mqtt-consumer/tests
    data/timeseries/tests
    examples/machine-metrics/tests
pythonpath =
    .
    operations/health/src
    operations/observability/src
    integration/rest-api/src
    integration/rest-source/src
    integration/mqtt-consumer/src
    data/timeseries/src
    examples/machine-metrics
