export {
  PLATFORM_GROUPS,
  PLATFORM_ROLES,
  GROUP_TO_ROLE,
  ROLE_RANK,
  GUEST_USER_ENTITY_REF,
  GUEST_GROUP_ENTITY_REF,
  ROLE_LABELS,
  parseGroupName,
  resolvePlatformRole,
  isAtLeast,
  isGuestIdentity,
  githubUserEntityRef,
  githubLoginFromEntityRef,
  platformGroupNames,
  hasApprovedPlatformAccess,
  URS_DOMAIN_GROUPS,
  URS_DOMAIN_PERMISSIONS,
  ursDomainPermissionNames,
} from './roles';
export type { PlatformGroup, PlatformRole, UrsDomainGroup } from './roles';

export {
  marketplaceViewPermission,
  marketplaceAdminPermission,
  dataProductViewPermission,
  dataProductCreatePermission,
  dataProductGovernancePermission,
  dataProductCertificationManagePermission,
  dataProductConsumePermission,
  dataProductViewQualityPermission,
  dataProductViewValidationPermission,
  dataProductAdminPermission,
  platformAdminPermission,
  templateAdminPermission,
  goldenPathReleaseManagePermission,
  aasReadPermission,
  aasManagePermission,
  entitlementViewPermission,
  entitlementAdminPermission,
  validationReadPermission,
  requirementReadPermission,
  traceabilityReadPermission,
  validationRunStartPermission,
  validationTestExecutePermission,
  validationReviewPermission,
  validationAdminPermission,
  validationApprovePermission,
  riskAcceptPermission,
  baselineModifyPermission,
  pluginDirectoryReadPermission,
  pluginDirectoryAdminPermission,
  modelCompanyReadPermission,
  modelCompanyRunScenarioPermission,
  modelCompanyControlPermission,
  modelCompanyAdminPermission,
  ursReadPermission,
  ursCreatePermission,
  ursManagePermission,
  ursApprovePermission,
  ursAdminPermission,
  ursSignPermission,
  ursChangeRequestManagePermission,
  businessCapabilityManagePermission,
  platformUserManagePermission,
  productReadPermission,
  productCreatePermission,
  productManagePermission,
  artifactReadPermission,
  artifactCreatePermission,
  artifactSubmitPermission,
  artifactReviewPermission,
  artifactCertifyPermission,
  artifactPublishPermission,
  artifactDeprecatePermission,
  publisherManagePermission,
  platformPermissions,
  VIEWER_PERMISSION_NAMES,
  DEVELOPER_PERMISSION_NAMES,
  OWNER_PERMISSION_NAMES,
  ADMIN_PERMISSION_NAMES,
  BUSINESS_CAPABILITY_LEAD_PERMISSION_NAMES,
} from './permissions';

export {
  permissionsForRole,
  decidePermission,
  canViewCatalog,
  canExecuteScaffolder,
  canCreateDataProduct,
  canManageGovernance,
  canCreateProduct,
  canManageProduct,
  canAdministerPlatform,
  canReadAas,
  canManageAas,
  canViewEntitlements,
  canAdministerEntitlements,
  canReadValidation,
  canStartValidationRun,
  canExecuteValidationTest,
  canReviewValidation,
  canAdministerValidation,
  canReadPluginDirectory,
  canAdministerPluginDirectory,
  canAdministerBusinessCapabilities,
  canManagePlatformUsers,
  canReadModelCompany,
  canRunModelCompanyScenario,
  canControlModelCompany,
  canAdministerModelCompany,
} from './policy';
export type { PolicyDecisionName, PolicyPermission } from './policy';

// URS vocabulary shared by the backend and the UI.
export {
  URSStatus,
  ChangeRequestStatus,
  ReviewScope,
  SignatureMeaning,
  SignatureTargetType,
  WorkflowStage,
  WorkflowState,
  URS_STATUS_LABELS,
  OPEN_URS_STATUSES,
  RELEASED_URS_STATUSES,
  ursStatusAppearance,
} from './urs';
export type { StatusAppearance } from './urs';

// Content hash binding electronic signatures to what was signed.
export {
  computeContentHash,
  canonicalizeContent,
  HASHED_CONTENT_FIELDS,
  CONTENT_HASH_ALGORITHM,
} from './content-hash';
export type { RequirementContent } from './content-hash';

// URS Composer → Validation Expert integration contract
export { VALIDATION_DECISION_STATUSES } from './validation-integration';
export type {
  ApprovedURSReference,
  ValidationContext,
  CreateValidationContextRequest,
  ValidationContextRequirement,
  ValidationDecision,
  ValidationDecisionStatus,
  CreateValidationDecisionRequest,
} from './validation-integration';

export { quickActionsForRole } from './dashboard';
export type { QuickAction } from './dashboard';

export {
  DEVELOPER_HUB_PATH,
  DEVELOPER_HUB_SECTIONS,
  DOCUMENTATION_OWNERS,
  DOCUMENTATION_PAGES,
  DOCUMENTATION_VERSION,
  APPLICABLE_PLATFORM,
  LAST_REVIEWED,
  ARCHITECTURE_STORY_PATH,
  DEVELOPER_ARCHITECTURE_PATH,
  DOC_AUDIENCES,
  DOC_SEARCH_KINDS,
  FIRST_DAY_STEPS,
  GOLDEN_PATH_DOC_SECTIONS,
  HUB_GOLDEN_PATHS,
  PLATFORM_DOCS_BASE,
  PLATFORM_DOCS_ENTITY_REF,
  SEARCH_PATH,
  classifyTechDocsResult,
  contextualDocumentationHref,
  developerHubActionsForRole,
  documentationFilePath,
  documentationHref,
  documentationPageById,
  documentationUrl,
  goldenPathDocumentationHref,
  isCustomerFacingAudience,
  publicCustomerAudiences,
  documentationIndexPages,
  AUDIENCE_LABELS,
  audienceLabel,
  documentationPagesForAudience,
  DOCUMENTATION_PERSONAS,
} from './documentation';
export type {
  ContextualDocContext,
  DeveloperHubAction,
  DeveloperHubSection,
  DocAudience,
  DocSearchKind,
  DocumentationPage,
  DocumentationPersona,
  FirstDayStep,
  HubGoldenPathCard,
} from './documentation';

export { formatJourneyError, isUnauthorizedError } from './journeyErrors';

export {
  decideSignInAccess,
  allowsGuestSignIn,
  allowsUnknownGithubUserSignIn,
  requiresCatalogUserApproval,
} from './accessPolicy';
export type { AuthEnvironment, SignInAccessDecision, SignInAccessInput } from './accessPolicy';

export {
  DEFAULT_ORGANIZATION,
  DEFAULT_ORGANIZATION_ID,
  DEFAULT_ORGANIZATION_NAME,
  DEFAULT_ORGANIZATION_SLUG,
  LEGACY_ORGANIZATION_ID,
  createDefaultOrganizationContext,
  isDefaultOrganization,
  resolveOrganizationId,
} from './organization';
export type {
  Organization,
  OrganizationContext,
  OrganizationIsolationMode,
} from './organization';

export {
  COMMERCIAL_ENVIRONMENTS,
  ENTITLEMENT_AUDIT_EVENTS,
  ENTITLEMENT_IDS,
  ENTITLEMENT_PROVIDER_IDS,
  ENTITLEMENT_SOURCES,
  ENTITLEMENT_STATUSES,
  FUTURE_ENTITLEMENTS,
  MVP_ENABLED_ENTITLEMENTS,
  USAGE_METERING_DIMENSIONS,
  DISTRIBUTION_DESTINATIONS,
  createDefaultEntitlementContext,
  createEntitlementAuditEvent,
  createEntitlementContext,
  createEntitlementRecord,
  createNoopUsageMeteringProvider,
  deriveEntitlementStatus,
  isActiveEntitlement,
  isMvpCapabilityEntitled,
  rejectSaasRegistration,
} from './entitlements';
export type {
  CommercialEnvironment,
  Entitlement,
  EntitlementAuditAuthorizationContext,
  EntitlementAuditEvent,
  EntitlementAuditEventType,
  EntitlementContext,
  EntitlementId,
  EntitlementProvider,
  EntitlementProviderId,
  EntitlementSource,
  EntitlementStatus,
  MarketplaceCustomerLink,
  SaasRegistrationRequest,
  SaasRegistrationResult,
  UsageMeteringDimension,
  UsageMeteringProvider,
  UsageMeteringRecord,
  CommercialDistributionRequest,
  CommercialDistributionResult,
  DistributionDestination,
} from './entitlements';

export {
  COMMERCIAL_AVAILABILITY,
  COMMERCIAL_CARD_STATUSES,
  COMMERCIAL_DISTRIBUTION_CHANNELS,
  COMMERCIAL_EDITIONS,
  COMMERCIAL_PRODUCT_IDS,
  COMMERCIAL_PRODUCT_TYPES,
  LEGACY_ENTITLEMENT_ALIASES,
  LOCAL_DEFAULT_PRODUCT_IDS,
  commercialAvailabilityCopy,
  commercialCardStatus,
  commercialProductForMarketplaceItem,
  commercialProductForTemplate,
  findCommercialProduct,
  isCommercialProductId,
  isCommerciallyOffered,
  loadCommercialProductCatalog,
  normalizeProductId,
} from './commercial-products';
export type {
  CommercialAvailability,
  CommercialCardStatus,
  CommercialDistributionChannel,
  CommercialEditionId,
  CommercialProduct,
  CommercialProductCatalog,
  CommercialProductId,
  CommercialProductType,
} from './commercial-products';

export {
  LocalEntitlementProvider,
  PlatformEntitlementService,
  commercialReleaseEligible,
  defaultEntitlementService,
} from './entitlement-service';
export type {
  CreateAuthorization,
  EntitlementService,
  LocalEntitlementConfig,
  PlatformEntitlementServiceOptions,
} from './entitlement-service';

export {
  CREATE_AUTHORIZATION_AUDIT_TYPES,
  FileCreateAuthorizationAuditStore,
  MemoryCreateAuthorizationAuditStore,
  isCreateAuthorizationAuditEvent,
} from './create-authorization-audit-store';
export type {
  CreateAuthorizationAuditIssue,
  CreateAuthorizationAuditIssueReason,
  CreateAuthorizationAuditStore,
} from './create-authorization-audit-store';

export {
  createIdentityContext,
  createMvpPlatformContext,
} from './identity-context';
export type {
  IdentityContext,
  IdentityContextInput,
  PlatformRuntimeContext,
} from './identity-context';

export {
  ROADMAP_GOLDEN_PATHS,
  showcaseGoldenPaths,
  GOLDEN_PATH_CATEGORIES,
  filterGoldenPaths,
  DEPLOYMENT_OPTIONS,
  ENTERPRISE_PRICING_CTA,
  HOW_IT_WORKS_STEPS,
  LEARN_ASSEMBLY_EXAMPLES,
  LEARN_ASSEMBLY_STEPS,
  LEARN_TOPICS,
  PLATFORM_CAPABILITIES,
  PRICING_MODELS,
  PRODUCT_EDITIONS,
  INTERNAL_OPERATING_EDITION,
  LEGAL_DISTRIBUTION_STATUS,
  parseLegalDistributionStatus,
  learnTopicHref,
} from './commercial';
export type {
  DeploymentKind,
  EditionAvailability,
  GoldenPathAvailability,
  GoldenPathCategory,
  GoldenPathShowcaseItem,
  LearnTopic,
  LegalDistributionStatus,
  OperatingEdition,
  OperatingEditionId,
  PricingModel,
  ProductEdition,
  ProductEditionId,
} from './commercial';

export {
  AVAILABLE_DISTRIBUTION_CHANNELS,
  DISTRIBUTION_AVAILABILITY,
  DISTRIBUTION_CHANNELS,
  DISTRIBUTION_DESCRIPTIONS,
  GOLDEN_PATH_LIFECYCLE_STATES,
  LIFECYCLE_TRANSITIONS,
  OFFICIAL_GOLDEN_PATHS,
  RELEASE_CATALOG_PATH,
  allowedLifecycleTransitions,
  applyReleaseOverrides,
  canApproveGoldenPathRelease,
  canCreateFromRelease,
  canCreateOfficialGoldenPath,
  canProposeGoldenPathRelease,
  canReviewGoldenPathCertification,
  canTransitionLifecycle,
  compareReleaseVersions,
  currentRelease,
  currentReleasedVersion,
  distributionLabel,
  distributionDescription,
  distributionStatusLines,
  evaluateTemplateReleaseUpgrade,
  filterReleaseCatalogRows,
  isGenerallyAvailableRelease,
  isOfficialGoldenPath,
  isRetiredRelease,
  isScaffolderTemplatePermission,
  isGoldenPathLifecycle,
  loadGoldenPathReleaseCatalog,
  loadGoldenPathReleases,
  releaseCatalogRows,
  releaseKey,
  releasesForTemplate,
  templateIdFromResourceRef,
  validateGoldenPathRelease,
  validateGoldenPathReleaseCatalog,
  visibleDistribution,
} from './releases';
export type {
  DistributionAvailability,
  DistributionChannel,
  GoldenPathChangelog,
  GoldenPathCertificationStatus,
  GoldenPathDeprecation,
  GoldenPathLifecycle,
  GoldenPathRelease,
  GoldenPathReleaseCatalog,
  OfficialGoldenPathId,
  ReleaseValidationIssue,
} from './releases';

export {
  PLATFORM_COMPONENT_CATEGORIES,
  PLATFORM_COMPONENT_CERTIFICATION_STATUSES,
  PLATFORM_COMPONENT_KIND_ANNOTATION,
  PLATFORM_COMPONENT_REGISTRY_PATH,
  PLATFORM_COMPONENT_TYPE,
  SUPPORTED_PLATFORM_COMPONENT_STATUSES,
  catalogGraphPathForRef,
  filterPlatformComponents,
  findPlatformComponent,
  isDeprecatedPlatformComponent,
  isPlatformComponentEntity,
  isSupportedPlatformComponent,
  isValidVersionConstraint,
  normalizeEntityRef,
  parsePlatformComponentCategory,
  parsePlatformComponentCertification,
  parsePlatformComponentVersion,
  platformComponentPath,
  toPlatformComponent,
  toRelatedPlatformComponents,
  versionSatisfiesConstraint,
} from './platform-components';
export type {
  CatalogEntityLike,
  PlatformComponent,
  PlatformComponentCategory,
  PlatformComponentCertificationStatus,
  PlatformComponentFilters,
} from './platform-components';

export {
  CATALOG_ONLY_COMPONENT_NAMES,
  CONFIG_KEY_TYPES,
  LIBRARY_COMPATIBILITY_FILTERS,
  LIBRARY_RUNTIME_FILTERS,
  LIBRARY_STATUS_FILTERS,
  PLATFORM_COMPONENT_CATEGORY_LABELS,
  RUNTIME_PACKAGE_COMPONENT_NAMES,
  RUNTIME_PACKAGE_SOURCE_PATHS,
  compositionSnippetFor,
  componentNameFromRef,
  filterLibraryComponents,
  hasRuntimePackage,
  libraryProfileFor,
  matchesStandard1x,
  builtWithSummary,
  runtimeAvailabilityFor,
  toLibraryComponents,
  usageLabelsForComponent,
} from './platform-component-library';
export type {
  ComponentLibraryProfile,
  ConfigKeySchema,
  ConfigKeyType,
  LibraryCompatibilityFilter,
  LibraryComponentFilters,
  LibraryPlatformComponent,
  LibraryRuntimeFilter,
  LibraryStatusFilter,
  BuiltWithItem,
  BuiltWithSummary,
  RuntimeAvailability,
} from './platform-component-library';

export {
  COMPOSER_COMPONENT_VERSION,
  COMPOSER_PATH,
  COMPOSER_STANDARD_RANGE,
  COMPOSER_STANDARD_VERSION,
  applyComposerQuery,
  composerArchitectureFromSelection,
  composerDisabledReason,
  composerDraftToManifest,
  composerPath,
  composerPresets,
  composerSelectionKind,
  dependencyLabelsFor,
  groupedLibraryComponents,
  isComposerSelectable,
  officialGoldenPathForDraft,
  officialGoldenPathForSelection,
  sanitizeComposerComponentQuery,
  compositionConfigSummary,
  serializeCompositionYaml,
  slugifyCompositionName,
  sortCompositionRefs,
  validateComposerDraft,
  yamlContainsSecrets,
} from './composer';
export type {
  ComposerArchitectureLayer,
  ComposerChecklist,
  ComposerDraft,
  ComposerPreset,
  ComposerSelectionKind,
  ComposerUxIssue,
  ComposerValidationView,
  CompositionConfigKey,
  CompositionConfigSummary,
} from './composer';

export {
  GOLDEN_PATH_COMPOSITION_API_VERSION,
  GOLDEN_PATH_COMPOSITION_KIND,
  compositionComponentRefs,
  compositionUsageFromManifests,
  compositionOfArtifactManifest,
  normalizeComposition,
  optionalCompositionComponentRefs,
  parseCompositionManifest,
  validateComposition,
} from './composition';
export type {
  CompositionIssue,
  CompositionIssueCode,
  CompositionValidationResult,
  CompositionUsage,
  CompositionUsageKind,
  GoldenPathComposition,
  GoldenPathCompositionComponent,
} from './composition';

export {
  COMPONENT_TYPES,
  REQUIREMENT_NATURES,
  CRITICALITIES,
  DATA_CLASSIFICATIONS,
  INTERFACE_TYPES,
  VALIDATION_LEVELS,
  AUTOMATION_READINESS_LEVELS,
  isComponentType,
  isRequirementNature,
  isCriticality,
  isDataClassification,
  isInterfaceType,
  isValidationLevel,
  isAutomationReadiness,
} from './classification';
export type {
  ComponentType,
  RequirementNature,
  Criticality,
  DataClassification,
  InterfaceType,
  ValidationLevel,
  AutomationReadiness,
  RequirementClassification,
} from './classification';

export {
  ARTIFACT_KINDS,
  ARTIFACT_LIFECYCLE_STATES,
  ARTIFACT_MANIFEST_API_VERSION,
  ARTIFACT_SEGMENT_MAX_LENGTH,
  artifactCoordinateOf,
  formatArtifactRef,
  isArtifactKind,
  isArtifactLifecycle,
  isArtifactManifest,
  isArtifactSegment,
  editionHasCapability,
  isPublisherTrustLevel,
  parseArtifactRef,
  validateArtifactManifest,
  PUBLISHER_TRUST_LEVELS,
} from './artifact';
export type {
  Artifact,
  ArtifactCertificationStatus,
  ArtifactCompositionComponent,
  ArtifactCoordinate,
  ArtifactKind,
  ArtifactLifecycle,
  ArtifactManifest,
  ArtifactVersion,
  EditionCatalogue,
  PlatformEdition,
  Publisher,
  PublisherTrustLevel,
} from './artifact';

export {
  MARKETPLACE_CATEGORY_KINDS,
  MARKETPLACE_OFFERING_STATUSES,
  MARKETPLACE_SPEC_KEY,
  UNCERTIFIED_STATUS,
  manifestsFromRegistry,
  marketplaceOfferingsFromRegistry,
  marketplaceViewOfManifest,
  representativeVersion,
} from './marketplace-artifact';
export type {
  MarketplaceManifestView,
  MarketplaceOfferingStatus,
  MarketplaceOfferingView,
  RegistryArtifactWithVersions,
} from './marketplace-artifact';

export {
  PRODUCT_TYPES,
  PRODUCT_LIFECYCLES,
  PRODUCT_STATUSES,
  PRODUCT_VERSION_STATUSES,
  DATA_CONTRACT_STATUSES,
  DATA_CONTRACT_SCHEMA_TYPES,
  TRACEABILITY_RELATIONSHIP_TYPES,
  PRODUCT_BASELINE_STATUSES,
  isProductType,
  isProductVersionStatus,
  isDataContractSchemaType,
  isDataContractStatus,
  isProductBaselineStatus,
  findVersionLabelClash,
  isVersionLabel,
  nextMajorVersionLabel,
  parseVersionLabel,
  validateBaselineLabel,
  validateDataContractSchemaType,
  validateProduct,
  validateVersionLabel,
  validateTraceabilityLink,
} from './product';
export {
  CONTRACT_ACCESS_MODES,
  COORDINATE_SEGMENT_MAX_LENGTH,
  QUALITY_RULE_TYPES,
  contractRef,
  isContractAccessMode,
  isNameSegment,
  isSameProvenance,
  parseContractRef,
  validateContractExchange,
  validateNameSegment,
  validateReleaseProvenance,
  SUBSCRIPTION_STATUSES,
  UPGRADE_NOTIFICATION_TYPES,
  isQualityRuleType,
} from './product';
export type {
  Product,
  ProductVersion,
  VersionLabelParts,
  ProductComponent,
  DataContract,
  ProductDependency,
  ContractAccessMode,
  ContractCoordinate,
  ContractExchange,
  ContractSla,
  ContractSubscription,
  TraceabilityLink,
  ProductBaseline,
  ReleaseProvenance,
  ProductType,
  ProductLifecycle,
  ProductStatus,
  ProductVersionStatus,
  ProductBaselineStatus,
  ProductChangeType,
  SnapshotItemChange,
  ProductBaselineDelta,
  DataContractStatus,
  DataContractSchemaType,
  TraceabilityRelationshipType,
  QualityRule,
  SubscriptionStatus,
  UpgradeNotification,
  UpgradeNotificationType,
  QualityRuleType,
} from './product';

export {
  CONTRACT_COMPAT_STATUSES,
  compareJsonSchemas,
  detectSchemaDrift,
  evaluateContractCompatibility,
  parseSemver as parseContractSemver,
} from './contract-compatibility';
export type {
  ContractCompatStatus,
  ContractCompatFinding,
  ContractCompatReport,
  JsonSchemaLike,
  SchemaDriftResult,
  SchemaSnapshot,
} from './contract-compatibility';

// Registry Federation types (W3-7 foundation)
export type {
  FederatedArtifact,
  FederatedRegistry,
  FederatedSearchResult,
  FederationConfig,
} from './registry-federation';

export {
  NEXORA_ANNOTATION_PREFIX,
  NEXORA_ANNOTATIONS,
  EQUIPMENT_COMPONENT_TYPE,
  EQUIPMENT_PATH,
  INDUSTRIAL_CONTRACTS_PATH,
  INDUSTRIAL_QUALITY_PATH,
  CONNECTIVITY_STATUSES,
  CONNECTIVITY_KINDS,
  HEALTH_STATES,
  EQUIPMENT_STATES,
  CONTRACT_COMPATIBILITY,
  CAPABILITY_LEVELS,
  apiDocsPath,
  catalogEntityPath,
  entityNameFromRef,
  entityRefOf,
  equipmentPath,
  filterAssets,
  filterIndustrialProducts,
  groupAssetsByHierarchy,
  hasIndustrialAnnotation,
  industrialContractPath,
  industrialQualityPath,
  interfaceLabels,
  isEquipmentEntity,
  isIndustrialDataProduct,
  okResult,
  parseCapabilityLevel,
  parseCompatibility,
  parseConnectivityStatus,
  parseEquipmentState,
  parseHealthState,
  relatedDataProducts,
  relatedResources,
  toIndustrialDataProduct,
  toNexoraAsset,
  unconfiguredResult,
  unavailableResult,
  uniqueValues,
} from './nexora-industrial';
export type {
  AssetFilters,
  CapabilityGroup,
  CapabilityItem,
  CapabilityLevel,
  ConnectivityInterface,
  ConnectivityKind,
  ConnectivityStatus,
  ContractCompatibility,
  ContractHistoryEntry,
  ContractView,
  DataProductHealth,
  DataProductRef,
  EquipmentRuntimeState,
  EquipmentStateView,
  HealthCheck,
  HealthState,
  IndustrialDataProduct,
  MetricValue,
  NexoraAsset,
  ProductFilters,
  ProviderResult,
  ProviderResultStatus,
} from './nexora-industrial';
