apiVersion: platform.nexora.io/v1alpha1
kind: DataProduct
metadata:
  name: ${{ values.name }}
  title: ${{ values.title }}
  description: ${{ values.description }}
spec:
  domain: ${{ values.domain }}
  owner: ${{ values.owner }}
  lifecycle: ${{ values.lifecycle }}
  interfaces:
    - id: query
      type: rest
      path: /api/v1/temperature
    - id: realtime
      type: stream
      protocol: sse
    - id: source
      type: mqtt
  contracts:
    outputs:
      - temperature-event-v1
  presentation:
    defaultView: timeseries
    capabilities:
      - table
      - metric-cards
      - timeseries
      - realtime
      - json
      - schema
  validation:
    status: NOT_VALIDATED
