#!/usr/bin/env bash
# Dev-environment helper for Ona / Gitpod workspaces.
#
# Two modes, because they have different constraints:
#
#   start  — webpack dev server on 3000 + backend on 7007, container-local.
#            Hot reload. Use it from inside the container.
#
#   serve  — ONE origin on 7007: the backend serves the built frontend, the
#            way the production image does. Required for the Ona gateway.
#            A split 3000/7007 setup cannot work through the gateway: a fetch
#            from the 3000 host to the 7007 host is cross-origin, the browser
#            withholds the gateway session cookie, and the gateway answers 401
#            with no CORS headers. One hostname removes the problem entirely.
#
# Three things are easy to get wrong by hand and are handled here:
#   1. a .env file — `yarn start` passes --env-file and node fails without it
#   2. no EMPTY variables — Backstage drops a config key whose ${VAR} is unset,
#      but rejects it with "got empty-string, wanted string" when it is set and
#      empty. Half the backend plugins refuse to start otherwise.
#   3. Guest sign-in is opt-in via AUTH_GUEST_ENABLED / AUTH_GUEST_ROLE.
#
# Exposing a port is deliberately never automatic.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OVERRIDE="$ROOT/.runtime/app-config.ona.yaml"   # .runtime/ is gitignored

# Node may come from the devcontainer feature or, before a rebuild, from a
# local install.
if ! command -v node >/dev/null 2>&1 && [ -x "$HOME/.local/node22/bin/node" ]; then
  export PATH="$HOME/.local/node22/bin:$PATH"
fi

# Reads a key from the process environment, falling back to .env. The script
# needs these flags before the app starts; only the app itself gets .env loaded
# by `node --env-file`.
env_value() {
  local key="$1"
  if [ -n "${!key:-}" ]; then
    printf '%s' "${!key}"
    return
  fi
  [ -f "$ROOT/.env" ] || return 0
  sed -n "s/^[[:space:]]*${key}=//p" "$ROOT/.env" \
    | tail -1 \
    | sed -e 's/^"\(.*\)"$/\1/' -e "s/^'\(.*\)'$/\1/" \
    | tr -d '\r'
}

ensure_env() {
  if [ -f "$ROOT/.env" ]; then
    return
  fi
  echo "Creating .env (BACKEND_SECRET only — see note 2 in this script)"
  cat > "$ROOT/.env" <<'EOF'
# Generated by scripts/ona-dev.sh. Gitignored. No real credentials.
# Optional integrations (GITHUB_TOKEN, COMPOSER_AI_KEY, AUTH_GITHUB_*) must
# stay ABSENT here. Setting them to an empty value breaks backend startup.
BACKEND_SECRET=dev-local-auth-key

# Guest sign-in. Without this the login offers GitHub only.
#   AUTH_GUEST_ENABLED=true   shows "Continue as Guest"
#   AUTH_GUEST_ROLE=viewer    read-only (default)
#   AUTH_GUEST_ROLE=developer additionally allows scaffolding and create
# AUTH_GUEST_ENABLED=true
# AUTH_GUEST_ROLE=viewer
EOF
}

# Config files shared by both modes, in merge order. repo start and package
# start resolve --config relative to the package, so these must be absolute.
base_config_args() {
  local -n out=$1
  out=(--config "$ROOT/app-config.yaml" --config "$ROOT/app-config.local.yaml")

  local guest_enabled guest_role
  guest_enabled="$(env_value AUTH_GUEST_ENABLED)"
  guest_role="$(env_value AUTH_GUEST_ROLE)"
  if [ "$guest_enabled" = "true" ]; then
    out+=(--config "$ROOT/app-config.guest.yaml")
    if [ "$guest_role" = "developer" ]; then
      out+=(--config "$ROOT/app-config.guest-developer.yaml")
      echo "Guest sign-in: enabled, role DEVELOPER (can scaffold and create)" >&2
    else
      echo "Guest sign-in: enabled, role VIEWER (read-only)" >&2
      if [ -n "$guest_role" ] && [ "$guest_role" != "viewer" ]; then
        echo "  note: AUTH_GUEST_ROLE='$guest_role' not recognised; using viewer" >&2
      fi
    fi
  else
    echo "Guest sign-in: disabled (set AUTH_GUEST_ENABLED=true in .env)" >&2
  fi
}

expose() {
  command -v ona >/dev/null 2>&1 || { echo "ona CLI not found — are you in an Ona workspace?" >&2; exit 1; }

  # Only 7007 is exposed. The frontend is served from the same port, so there
  # is no second hostname and therefore no cross-origin request.
  local url
  url="$(ona environment port open 7007 --name nexora --protocol http 2>&1 \
    | grep -oE 'https://[^[:space:]]+' | tail -1)"
  if [ -z "$url" ]; then
    echo "Could not determine the forwarded URL. Check 'ona environment port list'." >&2
    exit 1
  fi

  mkdir -p "$(dirname "$OVERRIDE")"
  cat > "$OVERRIDE" <<EOF
# Generated by scripts/ona-dev.sh expose. Gitignored, environment-specific.
# Single origin: the backend serves the frontend, same as the production image.
app:
  baseUrl: $url

backend:
  baseUrl: $url
  listen:
    host: 0.0.0.0
    port: 7007
  cors:
    origin: $url
    methods: [GET, HEAD, PATCH, POST, PUT, DELETE]
    credentials: true
EOF

  echo "URL: $url"
  echo "Wrote $OVERRIDE"
  echo
  echo "Next:"
  echo "  yarn workspace app build     # the backend serves this bundle"
  echo "  scripts/ona-dev.sh serve"
  echo
  echo "Sign in with 'Continue as Guest' (AUTH_GUEST_ENABLED=true in .env)."
  echo "GitHub login additionally needs AUTH_GITHUB_CLIENT_ID / _SECRET and an"
  echo "OAuth App callback URL of exactly:"
  echo "  $url/api/auth/github/handler/frame"
}

start() {
  ensure_env
  local args
  base_config_args args
  echo "Mode: dev server — http://localhost:3000 (container-local)"
  cd "$ROOT"
  exec node --env-file=.env ./node_modules/@backstage/cli/bin/backstage-cli \
    repo start "${args[@]}"
}

serve() {
  ensure_env
  if [ ! -f "$OVERRIDE" ]; then
    echo "No $OVERRIDE — run 'scripts/ona-dev.sh expose' first." >&2
    exit 1
  fi
  if [ ! -f "$ROOT/packages/app/dist/index.html" ]; then
    echo "No frontend bundle. Run 'yarn workspace app build' first." >&2
    exit 1
  fi
  local args
  base_config_args args
  args+=(--config "$OVERRIDE")
  echo "Mode: single origin on 7007 — backend serves the built frontend"
  cd "$ROOT/packages/backend"
  exec node --env-file="$ROOT/.env" \
    "$ROOT/node_modules/@backstage/cli/bin/backstage-cli" package start "${args[@]}"
}

ready() {
  curl -sf -o /dev/null http://127.0.0.1:7007/api/data-products/health
}

case "${1:-start}" in
  start)  start ;;
  serve)  serve ;;
  expose) expose ;;
  ready)  ready ;;
  env)    ensure_env ;;
  *)      echo "usage: ona-dev.sh [start|serve|expose|ready|env]" >&2; exit 2 ;;
esac
