#!/usr/bin/env bash
# Dev-environment helper for Ona / Gitpod workspaces.
#
# The app needs three things that are easy to get wrong by hand:
#   1. a .env file — `yarn start` passes --env-file and node fails without it
#   2. no EMPTY variables — Backstage drops a config key whose ${VAR} is unset,
#      but rejects it with "got empty-string, wanted string" when it is set and
#      empty. Half the backend plugins refuse to start otherwise.
#   3. when reaching the app through the Ona gateway: bind 0.0.0.0 and use the
#      forwarded https URLs, because the browser runs outside the container and
#      cannot resolve localhost:7007.
#
# Exposing ports is deliberately NOT automatic. Run `ona-dev.sh expose` when you
# want the app reachable from outside; the default start stays container-local.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OVERRIDE="$ROOT/.runtime/app-config.ona.yaml"   # .runtime/ is gitignored

# Node may come from the devcontainer feature or, before a rebuild, from a
# local install.
if ! command -v node >/dev/null 2>&1 && [ -x "$HOME/.local/node22/bin/node" ]; then
  export PATH="$HOME/.local/node22/bin:$PATH"
fi

ensure_env() {
  if [ -f "$ROOT/.env" ]; then
    return
  fi
  echo "Creating .env (BACKEND_SECRET only — see note 2 in this script)"
  cat > "$ROOT/.env" <<'EOF'
# Generated by scripts/ona-dev.sh. Gitignored. No real credentials.
# Optional integrations (GITHUB_TOKEN, COMPOSER_AI_KEY, AUTH_GITHUB_*) must
# stay ABSENT here. Setting them to an empty value breaks backend startup.
BACKEND_SECRET=dev-local-auth-key
EOF
}

port_url() {
  # Opens the port if needed and prints its URL. creator_only is the CLI
  # default; we never widen it here.
  local port="$1" name="$2" protocol="$3"
  ona environment port open "$port" --name "$name" --protocol "$protocol" 2>&1 \
    | grep -oE 'https://[^[:space:]]+' | tail -1
}

expose() {
  command -v ona >/dev/null 2>&1 || { echo "ona CLI not found — are you in an Ona workspace?" >&2; exit 1; }

  # The dev server switches itself to HTTPS once app.baseUrl is https, so the
  # gateway must speak https to port 3000. The backend stays plain HTTP.
  local app_url backend_url
  app_url="$(port_url 3000 frontend https)"
  backend_url="$(port_url 7007 backend http)"

  if [ -z "$app_url" ] || [ -z "$backend_url" ]; then
    echo "Could not determine the forwarded URLs. Check 'ona environment port list'." >&2
    exit 1
  fi

  mkdir -p "$(dirname "$OVERRIDE")"
  cat > "$OVERRIDE" <<EOF
# Generated by scripts/ona-dev.sh expose. Gitignored, environment-specific.
app:
  baseUrl: $app_url
  listen:
    host: 0.0.0.0
    port: 3000

backend:
  baseUrl: $backend_url
  listen:
    host: 0.0.0.0
    port: 7007
  cors:
    origin:
      - $app_url
    methods: [GET, HEAD, PATCH, POST, PUT, DELETE]
    credentials: true
EOF

  echo "Frontend: $app_url"
  echo "Backend:  $backend_url"
  echo "Wrote $OVERRIDE — restart the app for it to take effect."
  echo
  echo "Sign in with 'Continue as Guest'. GitHub login needs real OAuth"
  echo "credentials in .env (AUTH_GITHUB_CLIENT_ID / _SECRET) and the OAuth"
  echo "App's callback URL set to exactly:"
  echo "  $backend_url/api/auth/github/handler/frame"
}

start() {
  ensure_env
  # repo start resolves --config relative to each package, so these must be
  # absolute paths.
  local args=(--config "$ROOT/app-config.yaml" --config "$ROOT/app-config.local.yaml")
  if [ -f "$OVERRIDE" ]; then
    echo "Using gateway override $OVERRIDE"
    args+=(--config "$OVERRIDE")
  fi
  cd "$ROOT"
  exec node --env-file=.env ./node_modules/@backstage/cli/bin/backstage-cli repo start "${args[@]}"
}

ready() {
  curl -sf -o /dev/null http://127.0.0.1:7007/api/data-products/health
}

case "${1:-start}" in
  start)  start ;;
  expose) expose ;;
  ready)  ready ;;
  env)    ensure_env ;;
  *)      echo "usage: ona-dev.sh [start|expose|ready|env]" >&2; exit 2 ;;
esac
